#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Class {
    Arrow,
    Asterisk,
    BraceLeft,
    BraceRight,
    Comma,
    Dash,
    Equal,
    Identifier,
    Let,
    Number,
    ParenthesisLeft,
    ParenthesisRight,
    Plus,
    Return,
    Semicolon,
    Slash,
    Unknown,
}